### ISSUE TITLE
Min Relay Fee not met for sub-assets

### ISSUE THREAD

**Issue by RossClelland** [RavenProject/Ravencoin#428] opened 2018-11-06 05:58 UTC
#### If so, please list the steps to reproduce below:
1. Select Create New asset
2. Select "Sub-Asset" type
3. Try to issue a sub-asset

### Expected behaviour
Sub-asset is issued for 100rvn

### Actual behaviour
Error: The transaction was rejected! Reason given: min relay fee not met.

### Screenshots.
![screen](https://user-images.githubusercontent.com/34719071/48045614-f068c500-e188-11e8-81c5-2387901f813d.png)

### What version of rvn-core are you using?
2.1.2

### Machine specs:
- OS: windows

**Comment by blacklig** [comment] 2018-11-06 06:37
I have this error and was not doing what is stated above. It is for my BEER token which I yesterday (or lets say like 10 hours ago) was able to send to like 30 addresses. Today at the morning, I wanted to continue with donations and this happens:
![image](https://user-images.githubusercontent.com/32385597/48046960-9ff86400-e196-11e8-9cd5-7f4440bf2ce5.png)
![image](https://user-images.githubusercontent.com/32385597/48046969-a8e93580-e196-11e8-9acb-37d2bcf03cf4.png)

OS: OSX Mojave 10.14. Wallet compiled by myself from source 2.1.2

**Comment by bedri** [comment] 2018-11-06 08:06
Can you both state if the issue is on mainnet or testnet please? It's importantant for to checker of the problem.
Thanks in advanve.

**Comment by RossClelland** [comment] 2018-11-06 09:20
It's on the mainnet. Let me know if there's anything else I can provide to assist analysis.

**Comment by blacklig** [comment] 2018-11-06 12:08
> Can you both state if the issue is on mainnet or testnet please? It's important for the checker of the problem.
> Thanks in advance.

mainnet of course

**Comment by RossClelland** [comment] 2018-11-06 15:34
Thanks. I'll give it a try later this evening.

**Comment by blondfrogs** [comment] 2018-11-06 21:37
Fixed in release 2.1.3 binaries will be out soon.

**Comment by RossClelland** [comment] 2018-11-06 21:55
The workaround above worked fine for the time being

> As a temporary workaround, you can enable Fee Control in Settings -> Options -> Wallet, and increase the fee per kB up to 0.0001 RVN/kB.

**Closed** 2018-12-14 21:50 UTC
