### ISSUE TITLE
Library not loaded: @loader_path/libboost_system-mt.dylib Mac OS High Sierra 10.13.5

### ISSUE THREAD

**Issue by russkidooski** [RavenProject/Ravencoin#220] opened 2018-08-14 19:23 UTC
Process:               Raven-Qt [3593]
Path:                  /Applications/Raven-Qt.app/Contents/MacOS/Raven-Qt
Identifier:            org.ravenfoundation.Raven-Qt
Version:               2.0.3 (2.0.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Raven-Qt [3593]
User ID:               501
 
Date/Time:             2018-08-14 14:15:29.565 -0500
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Anonymous UUID:        B8FE026A-379A-8913-C9CD-D2C11F747654
 
Sleep/Wake UUID:       0CA69727-1927-494F-9C79-AF8B915B2698
 
Time Awake Since Boot: 430000 seconds
Time Since Wake:       360 seconds
 
System Integrity Protection: enabled
 
Crashed Thread:        0
 
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
 
Termination Reason:    DYLD, [0x1] Library missing
 
Application Specific Information:
dyld: launch, loading dependent libraries
 
Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found
 
Binary Images:
       0x10dee5000 -        0x10ea01fff +org.ravenfoundation.Raven-Qt (2.0.3 - 2.0.3) <F12AAE7C-328D-3B8F-941F-46384EAE52E5> /Applications/Raven-Qt.app/Contents/MacOS/Raven-Qt
       0x10eb36000 -        0x10eb38ff7 +libboost_system.dylib (0) <6D4202B3-758D-3014-A208-8577024B9BB3> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10eb42000 -        0x10eb51ff7 +libboost_filesystem.dylib (0) <BDEC6C74-6778-342E-AFF0-62ABA7D03E43> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10eb60000 -        0x10eb92fff +libboost_program_options-mt.dylib (0) <AEDAEFBB-E939-3404-BD07-2313425473FA> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10ebb3000 -        0x10ebc0fff +libboost_thread-mt.dylib (0) <CE22F73C-D5EA-32D9-A732-D824D54D622C> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10ebcc000 -        0x10ebcfff7 +libboost_chrono-mt.dylib (0) <19312DE7-D906-321B-9A48-5822E962A2EB> /Applications/Raven-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10ebd7000 -        0x10ecd6ff7 +QtNetwork (0) <5257AB18-D1CB-37F2-AF42-C2CDD10DFA03> /Applications/Raven-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10ed1c000 -        0x10f167fff +QtWidgets (0) <F20A9B73-EBF8-365F-9572-9F51B039A463> /Applications/Raven-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10f2c6000 -        0x10f6d2fff +QtGui (0) <E72E3A29-2517-354E-8F35-252FD61CD17E> /Applications/Raven-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10f7ca000 -        0x10fc91ff3 +QtCore (0) <783611A1-EDF8-381F-B30A-700D5BF1CA8E> /Applications/Raven-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10fd45000 -        0x10fd9fff7 +QtDBus (0) <2F2C2631-9C4E-33B2-93F7-768791CB6864> /Applications/Raven-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10fdbd000 -        0x10feefffb +libprotobuf.15.dylib (0) <2C6A5B36-5066-362A-91D7-06C58D3480D8> /Applications/Raven-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x10ffa3000 -        0x1100c7ff7 +libdb_cxx-4.8.dylib (0) <5EAB4A5B-9B72-3AFC-865E-016E1223F47F> /Applications/Raven-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x110104000 -        0x110143fff +libssl.1.0.0.dylib (0) <4D343D8E-B72A-38BD-9204-CC0354C0B7F8> /Applications/Raven-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x110160000 -        0x1102d0d67 +libcrypto.1.0.0.dylib (0) <4A0A66FE-A6B9-387F-B265-512C91DF46F9> /Applications/Raven-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x11033f000 -        0x110347ff3 +libminiupnpc.16.dylib (0) <C0328337-BDDE-37CA-9D40-BA304D48EE87> /Applications/Raven-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x11034d000 -        0x11034efff +libevent_pthreads-2.1.6.dylib (0) <6F618640-46F3-3B56-A22C-26941B4D8790> /Applications/Raven-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x110355000 -        0x110382fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/Raven-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x11447e000 -        0x1144c89df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff33921000 -     0x7fff3477ffff  com.apple.AppKit (6.9 - 1561.40.112) <2D9940B9-9C9B-3FF1-8E9F-26CD7E7E3B5A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff347d1000 -     0x7fff347d1fff  com.apple.ApplicationServices (48 - 50) <7BD49390-6D89-3429-80CD-6C70334F9B49> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff36345000 -     0x7fff367e6fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff374be000 -     0x7fff374befff  com.apple.CoreServices (822.33 - 822.33) <1AC8CE39-003D-3901-909F-2DE6838AF097> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff384a6000 -     0x7fff3886cfff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5b9b4000 -     0x7fff5b9e7ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff5beee000 -     0x7fff5beefffb  libSystem.B.dylib (1252.50.4) <CDA73F3E-2A7D-3354-818A-580317A03255> /usr/lib/libSystem.B.dylib
    0x7fff5c123000 -     0x7fff5c179fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff5c17a000 -     0x7fff5c19eff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5d5a6000 -     0x7fff5d9947e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff5e06a000 -     0x7fff5e06eff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff5e06f000 -     0x7fff5e079ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5e07a000 -     0x7fff5e081fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5e082000 -     0x7fff5e08bffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5e08c000 -     0x7fff5e111fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5e199000 -     0x7fff5e1d2ff7  libdispatch.dylib (913.60.2) <414353F7-3A9F-3091-AFCE-E66F74687D5D> /usr/lib/system/libdispatch.dylib
    0x7fff5e1d3000 -     0x7fff5e1f0ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff5e1f1000 -     0x7fff5e1f1ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff5e1ff000 -     0x7fff5e1ffff7  liblaunch.dylib (1205.60.9) <4B2943A9-0994-3E8B-94B8-98DA9CED0021> /usr/lib/system/liblaunch.dylib
    0x7fff5e200000 -     0x7fff5e204ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff5e205000 -     0x7fff5e207ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff5e208000 -     0x7fff5e209ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff5e20a000 -     0x7fff5e221fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff5e222000 -     0x7fff5e222fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5e223000 -     0x7fff5e2acff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff5e2ad000 -     0x7fff5e2b0ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5e2b1000 -     0x7fff5e2b4ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5e2b5000 -     0x7fff5e2b6fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5e2b7000 -     0x7fff5e2bdff7  libsystem_dnssd.dylib (878.50.17) <C12E2075-3E4B-3187-8B3B-F6150FCB82E0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5e2be000 -     0x7fff5e307ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff5e308000 -     0x7fff5e32eff7  libsystem_kernel.dylib (4570.61.1) <D7F2010A-EA32-3F62-90DE-85E3C5CC3065> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5e32f000 -     0x7fff5e37afcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff5e37b000 -     0x7fff5e39afff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5e39b000 -     0x7fff5e4cbff7  libsystem_network.dylib (1229.60.3) <D17B38B7-BE5D-3A9C-9257-F045E7647E8A> /usr/lib/system/libsystem_network.dylib
    0x7fff5e4cc000 -     0x7fff5e4d6ffb  libsystem_networkextension.dylib (767.60.1) <1745C91F-9AF0-357D-BD40-34451A2D6A5E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5e4d7000 -     0x7fff5e4e0ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff5e4e1000 -     0x7fff5e4e8ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff5e4e9000 -     0x7fff5e4f4fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5e4f5000 -     0x7fff5e4f8fff  libsystem_sandbox.dylib (765.60.1) <E5DE4B2F-202D-3474-9F08-7CAB1501D411> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5e4f9000 -     0x7fff5e4faff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5e4fb000 -     0x7fff5e502ff7  libsystem_symptoms.dylib (820.60.2) <9C9E82AB-D1EE-3EC7-B20E-44338CE092AC> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5e503000 -     0x7fff5e516fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff5e518000 -     0x7fff5e51dff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff5e51e000 -     0x7fff5e54bfff  libxpc.dylib (1205.60.9) <16132357-B57A-35F5-B165-487D3F759F45> /usr/lib/system/libxpc.dylib
 
Model: MacBookPro11,1, BootROM MBP111.0146.B00, 2 processors, Intel Core i5, 2.6 GHz, 8 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.6f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en3
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0128F, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

**Comment by krisklosterman** [comment] 2018-08-15 18:28
Same issue on 
OS Version:            Mac OS X 10.13.6

**Comment by darval** [comment] 2018-08-16 10:34
Looks like this is a duplicate of #181

**Comment by TronBlack** [comment] 2018-08-18 19:09
Yes, duplicate of 181

**Closed** 2018-08-18 19:54 UTC
