### ISSUE TITLE
Fatal error after compilation (Raven 3.3.2.0 on Linux Ubuntu 19.10 EOAN on Arm cortex-A72)

### ISSUE THREAD

**Issue by mdhak83** [RavenProject/Ravencoin#759] opened 2020-03-08 10:59 UTC
## Describe the issue

After building Ravencore 3.3.2 from sources on Linux (arm64) in a VM, I systematically get a segmentation fault while running.
I then tried to use the binaries (gnueabithf) and I ran the test cases. Here is the result I get :
test_raven
```
Running 318 test cases...
unknown location(0): fatal error: in "accounting_tests/acc_orderupgrade_test": memory access violation at address: 0x00000001: no mapping at fault address
wallet/test/accounting_tests.cpp(32): last checkpoint: "acc_orderupgrade_test" fixture ctor

*** 1 failure is detected in the test module "Raven Test Suite"
test_raven: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:85: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
Aborted (core dumped)

```

### Machine specs:
- OS: Ubuntu 19.10 eoan
- CPU: (Freebox Virtual Machine 2-CPU Arm Cortex-A72 aarch64 Little Endian 32&64-bits)
- RAM: 7 GB
- Disk size: 490 GB
- Disk Type (HD/SDD): HD

**Comment by blondfrogs** [comment] 2020-03-11 21:01
Are you using makecheck?

**Comment by mdhak83** [comment] 2020-03-12 06:29
> Are you using makecheck?

Yes.
However, I did restart my VM and it compiled fine yesterday.
I don't know what caused this.

**Comment by blondfrogs** [comment] 2020-04-21 19:51
Closing as the problem is solved

**Closed by blondfrogs** 2020-04-21 19:51 UTC
