### ISSUE TITLE
Ravencoin QT does not allow to issue Assets with more than 10 qty (textfield error)

### ISSUE THREAD

**Issue by vladaman** [RavenProject/Ravencoin#871] opened 2021-01-23 10:40 UTC
Using Raven Core version v4.3.2.1-25a2dbf41 (64-bit), Qt version 5.7.1. on Ubuntu 20.04 on testnet.

I am unable to create more than 10 qty of main or sub asset. The edit text does not permit to enter more than 10 qty.

![image](https://user-images.githubusercontent.com/907206/105575941-ae2efc80-5d6f-11eb-85b0-f0871a1620b4.png)

**Comment by lsji07** [comment] 2021-01-23 14:33
Duplicate of #830 worth noting it is on Ubuntu as well as Mac @TronBlack.

**Comment by fdoving** [comment] 2021-04-12 14:27
This issue should be fixed with PR #898.

**Comment by HyperPeek** [comment] 2021-04-18 09:49
I suggest to close

**Comment by hans-schmidt** [comment] 2021-04-23 17:40
I am closing it.

**Closed by hans-schmidt** 2021-04-23 17:40 UTC
