### ISSUE TITLE
./configure --disable-wallet fails make 

### ISSUE THREAD

**Issue by sjyi** [RavenProject/Ravencoin#46] opened 2018-03-06 05:38 UTC
### Describe the issue
If '--disable-wallet' is specified during configure, the make process fails at miner.cpp

### Can you reliably reproduce the issue?
Yes.  If '--disable-wallet' is not specified, make has no problem.

#### If so, please list the steps to reproduce below:
1. ./configure --disable-wallet
2. make
3.

### Screenshots.
libraven_server.a(libraven_server_a-miner.o): In function `GetFirstWallet()':
/home/sj/git/Ravencoin/src/miner.cpp:500: undefined reference to `vpwallets'
/home/sj/git/Ravencoin/src/miner.cpp:501: undefined reference to `vpwallets'
/home/sj/git/Ravencoin/src/miner.cpp:501: undefined reference to `vpwallets'
/home/sj/git/Ravencoin/src/miner.cpp:501: undefined reference to `vpwallets'
libraven_server.a(libraven_server_a-miner.o): In function `RavenMiner(CChainParams const&)':
/home/sj/git/Ravencoin/src/miner.cpp:514: undefined reference to `vpwallets'
libraven_server.a(libraven_server_a-miner.o):/home/sj/git/Ravencoin/src/miner.cpp:501: more undefined references to `vpwallets' follow
libraven_server.a(libraven_server_a-miner.o): In function `RavenMiner(CChainParams const&)':
/home/sj/git/Ravencoin/src/miner.cpp:521: undefined reference to `EnsureWalletIsAvailable(CWallet*, bool)'
/home/sj/git/Ravencoin/src/miner.cpp:531: undefined reference to `CWallet::GetScriptForMining(std::shared_ptr<CReserveScript>&)'
collect2: error: ld returned 1 exit status
Makefile:3835: recipe for target 'ravend' failed

### Machine specs:
- OS: Ubuntu 17.10
- CPU: x86_64
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by RavenMinerPool** [comment] 2018-04-06 07:39
FYI I also see this issue

**Comment by TronBlack** [comment] 2018-07-12 21:06
Will require wrapping mining and assets with #ifdef ENABLE_WALLET

**Comment by angelics** [comment] 2019-07-09 03:14
> libraven_server.a(libraven_server_a-miner.o): in function `GetFirstWallet()':
miner.cpp:(.text+0x3d8): undefined reference to `vpwallets'

compiling from 2.4.0 source. (i knw this is nt fixed in 2.4.0 release)
just to confirm that compiling with --disable-wallet stil fail.

**Comment by silence48** [comment] 2019-07-09 06:53
That undefined reference error is usually caused by some type of missing
dependencies most often the incorrect verson of openssl or libssl-dev.
I would try downgrading to the version that is listed in the depends folder
and then try your make again.

**Comment by HyperPeek** [comment] 2021-04-17 22:41
Works now -- will close.

**Closed by HyperPeek** 2021-04-17 22:41 UTC
Labels: build oddities
